using Business;
using DataAccess.Abstract;
using DataAccess.Concrete;
using DevExpress.ClipboardSource.SpreadsheetML;
using DevExpress.XtraExport.Helpers;
using DevExpress.XtraGrid.Columns;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace UI_Store
{
    public partial class FrmCompanies : Form
    {
        CompanyManager companyManager;
        int id;
        byte[] img = null;
        public FrmCompanies()
        {
            InitializeComponent();
            companyManager = CompanyManager.GetInstance();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void FrmCompanies_Load(object sender, EventArgs e)
        {
            CompaniesDataTable();
        }

        public void CompaniesDataTable()
        {
            gridControl1.DataSource = companyManager.GetDataTable();
            gridView1.OptionsView.ColumnAutoWidth = false;
            gridView1.Columns["ID"].Visible = false;
            gridView1.Columns["PHONE1"].Visible = false;
            gridView1.Columns["PHONE2"].Visible = false;
            gridView1.Columns["EMAIL"].Visible = false;
            gridView1.Columns["FAX"].Visible = false;
            gridView1.Columns["SECTOR"].Visible = false;
            gridView1.Columns["TAXOFFICE"].Visible = false;
            gridView1.Columns["SPECIALCODE1"].Visible = false;
            gridView1.Columns["SPECIALCODE2"].Visible = false;
            gridView1.Columns["SPECIALCODE3"].Visible = false;

            gridView1.Columns["IMAGE"].Width = 128;
            gridView1.Columns["TAXNO"].Width = 100;
            gridView1.Columns["COMPANY"].Width = 170;
            gridView1.Columns["AUTH_STATUS"].Width = 130;
            gridView1.Columns["AUTH_NAME_SUR"].Width = 130;
            gridView1.Columns["PROVINCE"].Width = 130;
            gridView1.Columns["DISTRICT"].Width = 130;
            gridView1.Columns["ADRESS"].Width = 330;
            gridView1.Columns["DETAILS"].Width = 70;
        }

        FrmCompanyDetails frm = new FrmCompanyDetails();
        private void repositoryItemButtonEdit1_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            frm.ShowDialog();
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            DataRow dataRow = gridView1.GetDataRow(gridView1.FocusedRowHandle);

            if (dataRow["IMAGE"].ToString() != "")
            {
                img = (byte[])dataRow["IMAGE"];
                if (img == null)
                {
                    frm.Pctbox1.Image = null;
                }
                MemoryStream ms = new MemoryStream(img);
                frm.Pctbox1.Image = Image.FromStream(ms);
                frm.img = img;
            }
            else
            {
                frm.Pctbox1.Image = null;
            }

            id = dataRow["ID"].ConInt();
            frm.province = (string)dataRow["PROVINCE"];
            frm.distrrict = Convert.ToString(dataRow["DISTRICT"]);
            frm.LblId.Text = id.ToString();
            frm.oldTaxno = dataRow["TAXNO"].ToString();
            frm.TxtCompany.Text = dataRow["COMPANY"].ToString();
            frm.TxtPosition.Text = dataRow["AUTH_STATUS"].ToString();
            frm.TxtAuthPerson.Text = dataRow["AUTH_NAME_SUR"].ToString();
            frm.TxtSector.Text = dataRow["SECTOR"].ToString();
            frm.MskPhone1.Text = dataRow["PHONE1"].ToString();
            frm.MskPhone2.Text = dataRow["PHONE2"].ToString();
            frm.TxtEmail.Text = dataRow["EMAIL"].ToString();
            frm.MskFax.Text = dataRow["FAX"].ToString();
            frm.RchAdress.Text = dataRow["ADRESS"].ToString();
            frm.TxtTaxOffice.Text = dataRow["TAXOFFICE"].ToString();
            frm.TxtSC1.Text = dataRow["SPECIALCODE1"].ToString();
            frm.TxtSC2.Text = dataRow["SPECIALCODE2"].ToString();
            frm.TxtSC3.Text = dataRow["SPECIALCODE3"].ToString();
        }

        private void BttnDelete_Click(object sender, EventArgs e)
        {
            if (DialogResult.Yes == MessageBox.Show("Are you sure you want to permanently delete this compay ?", "Delete Company", MessageBoxButtons.YesNo, MessageBoxIcon.Question))
            {
                MessageBox.Show(companyManager.Delete(id), "Deleting", MessageBoxButtons.OK, MessageBoxIcon.Hand);
            }
            CompaniesDataTable();
        }
        private void BttnAddCompany_Click(object sender, EventArgs e)
        {
            FrmCompaniesAdd frm = new FrmCompaniesAdd();
            frm.ShowDialog();
        }
    }
}
